# Netlify configuration for SurveyServe SPA routing
[build]
  publish = "dist"
  command = "npm run build"

# Client-side routing redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects (if using Supabase edge functions)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"