/*
  # SurveyServe Database Schema

  1. New Tables
    - `researchers`
      - `id` (uuid, primary key)
      - `email` (text, unique)
      - `name` (text)
      - `created_at` (timestamp)
    - `surveys`
      - `id` (uuid, primary key)
      - `title` (text)
      - `description` (text)
      - `version` (text)
      - `source` (text)
      - `schema` (jsonb) - Full survey definition including questions and scoring rules
      - `created_at` (timestamp)
    - `survey_links`
      - `id` (uuid, primary key)
      - `survey_id` (uuid, foreign key)
      - `researcher_id` (uuid, foreign key)
      - `link_code` (text, unique)
      - `max_responses` (integer)
      - `expires_at` (timestamp)
      - `allow_anonymous` (boolean)
      - `require_consent` (boolean)
      - `active` (boolean)
      - `created_at` (timestamp)
    - `responses`
      - `id` (uuid, primary key)
      - `survey_link_id` (uuid, foreign key)
      - `respondent_identifier` (text, nullable)
      - `raw_responses` (jsonb)
      - `computed_scores` (jsonb)
      - `completed_at` (timestamp)
    - `response_counts`
      - `survey_link_id` (uuid, primary key, foreign key)
      - `total_responses` (integer)
      - `last_updated` (timestamp)

  2. Security
    - Enable RLS on all tables
    - Add policies for researchers to access only their own data
    - Allow public access to survey taking endpoints
*/

-- Researchers table
CREATE TABLE IF NOT EXISTS researchers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text UNIQUE NOT NULL,
  name text NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE researchers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Researchers can read own data"
  ON researchers
  FOR SELECT
  TO authenticated
  USING (auth.uid() = id);

-- Surveys table (contains survey definitions)
CREATE TABLE IF NOT EXISTS surveys (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text NOT NULL,
  version text DEFAULT '1.0',
  source text NOT NULL,
  schema jsonb NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE surveys ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read surveys"
  ON surveys
  FOR SELECT
  TO authenticated, anon
  USING (true);

-- Survey links (generated by researchers)
CREATE TABLE IF NOT EXISTS survey_links (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  survey_id uuid NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
  researcher_id uuid NOT NULL REFERENCES researchers(id) ON DELETE CASCADE,
  link_code text UNIQUE NOT NULL DEFAULT encode(gen_random_bytes(16), 'hex'),
  max_responses integer DEFAULT 100,
  expires_at timestamptz,
  allow_anonymous boolean DEFAULT true,
  require_consent boolean DEFAULT true,
  active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE survey_links ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Researchers can manage own survey links"
  ON survey_links
  FOR ALL
  TO authenticated
  USING (auth.uid() = researcher_id);

CREATE POLICY "Anyone can read active survey links"
  ON survey_links
  FOR SELECT
  TO anon
  USING (active = true AND (expires_at IS NULL OR expires_at > now()));

-- Responses table
CREATE TABLE IF NOT EXISTS responses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  survey_link_id uuid NOT NULL REFERENCES survey_links(id) ON DELETE CASCADE,
  respondent_identifier text,
  raw_responses jsonb NOT NULL,
  computed_scores jsonb NOT NULL,
  completed_at timestamptz DEFAULT now()
);

ALTER TABLE responses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Researchers can read responses for their surveys"
  ON responses
  FOR SELECT
  TO authenticated
  USING (
    survey_link_id IN (
      SELECT id FROM survey_links WHERE researcher_id = auth.uid()
    )
  );

CREATE POLICY "Anyone can insert responses"
  ON responses
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- Response counts for efficient dashboard queries
CREATE TABLE IF NOT EXISTS response_counts (
  survey_link_id uuid PRIMARY KEY REFERENCES survey_links(id) ON DELETE CASCADE,
  total_responses integer DEFAULT 0,
  last_updated timestamptz DEFAULT now()
);

ALTER TABLE response_counts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Researchers can read response counts for their surveys"
  ON response_counts
  FOR SELECT
  TO authenticated
  USING (
    survey_link_id IN (
      SELECT id FROM survey_links WHERE researcher_id = auth.uid()
    )
  );

-- Function to update response counts
CREATE OR REPLACE FUNCTION update_response_count()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO response_counts (survey_link_id, total_responses, last_updated)
  VALUES (NEW.survey_link_id, 1, now())
  ON CONFLICT (survey_link_id)
  DO UPDATE SET
    total_responses = response_counts.total_responses + 1,
    last_updated = now();
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to automatically update response counts
DROP TRIGGER IF EXISTS trigger_update_response_count ON responses;
CREATE TRIGGER trigger_update_response_count
  AFTER INSERT ON responses
  FOR EACH ROW
  EXECUTE FUNCTION update_response_count();

-- Insert sample surveys
INSERT INTO surveys (title, description, source, schema) VALUES
(
  'Patient Health Questionnaire-9 (PHQ-9)',
  'A 9-question instrument for screening, diagnosing, monitoring and measuring the severity of depression.',
  'Kroenke, K., Spitzer, R. L., & Williams, J. B. (2001)',
  '{
    "questions": [
      {
        "id": "q1",
        "text": "Little interest or pleasure in doing things",
        "type": "likert",
        "options": [
          {"value": 0, "label": "Not at all"},
          {"value": 1, "label": "Several days"},
          {"value": 2, "label": "More than half the days"},
          {"value": 3, "label": "Nearly every day"}
        ],
        "reverse_score": false
      },
      {
        "id": "q2", 
        "text": "Feeling down, depressed, or hopeless",
        "type": "likert",
        "options": [
          {"value": 0, "label": "Not at all"},
          {"value": 1, "label": "Several days"},
          {"value": 2, "label": "More than half the days"},
          {"value": 3, "label": "Nearly every day"}
        ],
        "reverse_score": false
      },
      {
        "id": "q3",
        "text": "Trouble falling or staying asleep, or sleeping too much",
        "type": "likert",
        "options": [
          {"value": 0, "label": "Not at all"},
          {"value": 1, "label": "Several days"},
          {"value": 2, "label": "More than half the days"},
          {"value": 3, "label": "Nearly every day"}
        ],
        "reverse_score": false
      },
      {
        "id": "q4",
        "text": "Feeling tired or having little energy",
        "type": "likert",
        "options": [
          {"value": 0, "label": "Not at all"},
          {"value": 1, "label": "Several days"},
          {"value": 2, "label": "More than half the days"},
          {"value": 3, "label": "Nearly every day"}
        ],
        "reverse_score": false
      },
      {
        "id": "q5",
        "text": "Poor appetite or overeating",
        "type": "likert",
        "options": [
          {"value": 0, "label": "Not at all"},
          {"value": 1, "label": "Several days"},
          {"value": 2, "label": "More than half the days"},
          {"value": 3, "label": "Nearly every day"}
        ],
        "reverse_score": false
      },
      {
        "id": "q6",
        "text": "Feeling bad about yourself — or that you are a failure or have let yourself or your family down",
        "type": "likert",
        "options": [
          {"value": 0, "label": "Not at all"},
          {"value": 1, "label": "Several days"},
          {"value": 2, "label": "More than half the days"},
          {"value": 3, "label": "Nearly every day"}
        ],
        "reverse_score": false
      },
      {
        "id": "q7",
        "text": "Trouble concentrating on things, such as reading the newspaper or watching television",
        "type": "likert",
        "options": [
          {"value": 0, "label": "Not at all"},
          {"value": 1, "label": "Several days"},
          {"value": 2, "label": "More than half the days"},
          {"value": 3, "label": "Nearly every day"}
        ],
        "reverse_score": false
      },
      {
        "id": "q8",
        "text": "Moving or speaking so slowly that other people could have noticed? Or the opposite — being so fidgety or restless that you have been moving around a lot more than usual",
        "type": "likert",
        "options": [
          {"value": 0, "label": "Not at all"},
          {"value": 1, "label": "Several days"},
          {"value": 2, "label": "More than half the days"},
          {"value": 3, "label": "Nearly every day"}
        ],
        "reverse_score": false
      },
      {
        "id": "q9",
        "text": "Thoughts that you would be better off dead or of hurting yourself in some way",
        "type": "likert",
        "options": [
          {"value": 0, "label": "Not at all"},
          {"value": 1, "label": "Several days"},
          {"value": 2, "label": "More than half the days"},
          {"value": 3, "label": "Nearly every day"}
        ],
        "reverse_score": false
      }
    ],
    "scoring_rules": {
      "total_score": {
        "type": "sum",
        "questions": ["q1", "q2", "q3", "q4", "q5", "q6", "q7", "q8", "q9"]
      },
      "severity_level": {
        "type": "threshold",
        "input": "total_score",
        "thresholds": [
          {"min": 0, "max": 4, "label": "Minimal depression"},
          {"min": 5, "max": 9, "label": "Mild depression"},
          {"min": 10, "max": 14, "label": "Moderate depression"},
          {"min": 15, "max": 19, "label": "Moderately severe depression"},
          {"min": 20, "max": 27, "label": "Severe depression"}
        ]
      },
      "clinical_concern": {
        "type": "flag",
        "condition": "total_score >= 10",
        "message": "Score indicates moderate or higher depression severity"
      }
    }
  }'::jsonb
),
(
  'Generalized Anxiety Disorder 7-item (GAD-7)',
  'A self-administered patient questionnaire used to screen for and measure the severity of generalized anxiety disorder.',
  'Spitzer, R. L., Kroenke, K., Williams, J. B., & Löwe, B. (2006)',
  '{
    "questions": [
      {
        "id": "q1",
        "text": "Feeling nervous, anxious or on edge",
        "type": "likert",
        "options": [
          {"value": 0, "label": "Not at all"},
          {"value": 1, "label": "Several days"},
          {"value": 2, "label": "More than half the days"},
          {"value": 3, "label": "Nearly every day"}
        ],
        "reverse_score": false
      },
      {
        "id": "q2",
        "text": "Not being able to stop or control worrying",
        "type": "likert",
        "options": [
          {"value": 0, "label": "Not at all"},
          {"value": 1, "label": "Several days"},
          {"value": 2, "label": "More than half the days"},
          {"value": 3, "label": "Nearly every day"}
        ],
        "reverse_score": false
      },
      {
        "id": "q3",
        "text": "Worrying too much about different things",
        "type": "likert",
        "options": [
          {"value": 0, "label": "Not at all"},
          {"value": 1, "label": "Several days"},
          {"value": 2, "label": "More than half the days"},
          {"value": 3, "label": "Nearly every day"}
        ],
        "reverse_score": false
      },
      {
        "id": "q4",
        "text": "Trouble relaxing",
        "type": "likert",
        "options": [
          {"value": 0, "label": "Not at all"},
          {"value": 1, "label": "Several days"},
          {"value": 2, "label": "More than half the days"},
          {"value": 3, "label": "Nearly every day"}
        ],
        "reverse_score": false
      },
      {
        "id": "q5",
        "text": "Being so restless that it is hard to sit still",
        "type": "likert",
        "options": [
          {"value": 0, "label": "Not at all"},
          {"value": 1, "label": "Several days"},
          {"value": 2, "label": "More than half the days"},
          {"value": 3, "label": "Nearly every day"}
        ],
        "reverse_score": false
      },
      {
        "id": "q6",
        "text": "Becoming easily annoyed or irritable",
        "type": "likert",
        "options": [
          {"value": 0, "label": "Not at all"},
          {"value": 1, "label": "Several days"},
          {"value": 2, "label": "More than half the days"},
          {"value": 3, "label": "Nearly every day"}
        ],
        "reverse_score": false
      },
      {
        "id": "q7",
        "text": "Feeling afraid as if something awful might happen",
        "type": "likert",
        "options": [
          {"value": 0, "label": "Not at all"},
          {"value": 1, "label": "Several days"},
          {"value": 2, "label": "More than half the days"},
          {"value": 3, "label": "Nearly every day"}
        ],
        "reverse_score": false
      }
    ],
    "scoring_rules": {
      "total_score": {
        "type": "sum",
        "questions": ["q1", "q2", "q3", "q4", "q5", "q6", "q7"]
      },
      "severity_level": {
        "type": "threshold",
        "input": "total_score",
        "thresholds": [
          {"min": 0, "max": 4, "label": "Minimal anxiety"},
          {"min": 5, "max": 9, "label": "Mild anxiety"},
          {"min": 10, "max": 14, "label": "Moderate anxiety"},
          {"min": 15, "max": 21, "label": "Severe anxiety"}
        ]
      },
      "clinical_concern": {
        "type": "flag",
        "condition": "total_score >= 10",
        "message": "Score indicates moderate or higher anxiety severity"
      }
    }
  }'::jsonb
),
(
  'Big Five Inventory-10 (BFI-10)',
  'A short version of the Big Five personality inventory measuring openness, conscientiousness, extraversion, agreeableness, and neuroticism.',
  'Rammstedt, B., & John, O. P. (2007)',
  '{
    "questions": [
      {
        "id": "q1",
        "text": "I see myself as someone who is reserved",
        "type": "likert",
        "options": [
          {"value": 1, "label": "Disagree strongly"},
          {"value": 2, "label": "Disagree a little"},
          {"value": 3, "label": "Neither agree nor disagree"},
          {"value": 4, "label": "Agree a little"},
          {"value": 5, "label": "Agree strongly"}
        ],
        "reverse_score": true,
        "dimension": "extraversion"
      },
      {
        "id": "q2",
        "text": "I see myself as someone who is generally trusting",
        "type": "likert",
        "options": [
          {"value": 1, "label": "Disagree strongly"},
          {"value": 2, "label": "Disagree a little"},
          {"value": 3, "label": "Neither agree nor disagree"},
          {"value": 4, "label": "Agree a little"},
          {"value": 5, "label": "Agree strongly"}
        ],
        "reverse_score": false,
        "dimension": "agreeableness"
      },
      {
        "id": "q3",
        "text": "I see myself as someone who tends to be lazy",
        "type": "likert",
        "options": [
          {"value": 1, "label": "Disagree strongly"},
          {"value": 2, "label": "Disagree a little"},
          {"value": 3, "label": "Neither agree nor disagree"},
          {"value": 4, "label": "Agree a little"},
          {"value": 5, "label": "Agree strongly"}
        ],
        "reverse_score": true,
        "dimension": "conscientiousness"
      },
      {
        "id": "q4",
        "text": "I see myself as someone who is relaxed, handles stress well",
        "type": "likert",
        "options": [
          {"value": 1, "label": "Disagree strongly"},
          {"value": 2, "label": "Disagree a little"},
          {"value": 3, "label": "Neither agree nor disagree"},
          {"value": 4, "label": "Agree a little"},
          {"value": 5, "label": "Agree strongly"}
        ],
        "reverse_score": true,
        "dimension": "neuroticism"
      },
      {
        "id": "q5",
        "text": "I see myself as someone who has few artistic interests",
        "type": "likert",
        "options": [
          {"value": 1, "label": "Disagree strongly"},
          {"value": 2, "label": "Disagree a little"},
          {"value": 3, "label": "Neither agree nor disagree"},
          {"value": 4, "label": "Agree a little"},
          {"value": 5, "label": "Agree strongly"}
        ],
        "reverse_score": true,
        "dimension": "openness"
      },
      {
        "id": "q6",
        "text": "I see myself as someone who is outgoing, sociable",
        "type": "likert",
        "options": [
          {"value": 1, "label": "Disagree strongly"},
          {"value": 2, "label": "Disagree a little"},
          {"value": 3, "label": "Neither agree nor disagree"},
          {"value": 4, "label": "Agree a little"},
          {"value": 5, "label": "Agree strongly"}
        ],
        "reverse_score": false,
        "dimension": "extraversion"
      },
      {
        "id": "q7",
        "text": "I see myself as someone who tends to find fault with others",
        "type": "likert",
        "options": [
          {"value": 1, "label": "Disagree strongly"},
          {"value": 2, "label": "Disagree a little"},
          {"value": 3, "label": "Neither agree nor disagree"},
          {"value": 4, "label": "Agree a little"},
          {"value": 5, "label": "Agree strongly"}
        ],
        "reverse_score": true,
        "dimension": "agreeableness"
      },
      {
        "id": "q8",
        "text": "I see myself as someone who does a thorough job",
        "type": "likert",
        "options": [
          {"value": 1, "label": "Disagree strongly"},
          {"value": 2, "label": "Disagree a little"},
          {"value": 3, "label": "Neither agree nor disagree"},
          {"value": 4, "label": "Agree a little"},
          {"value": 5, "label": "Agree strongly"}
        ],
        "reverse_score": false,
        "dimension": "conscientiousness"
      },
      {
        "id": "q9",
        "text": "I see myself as someone who gets nervous easily",
        "type": "likert",
        "options": [
          {"value": 1, "label": "Disagree strongly"},
          {"value": 2, "label": "Disagree a little"},
          {"value": 3, "label": "Neither agree nor disagree"},
          {"value": 4, "label": "Agree a little"},
          {"value": 5, "label": "Agree strongly"}
        ],
        "reverse_score": false,
        "dimension": "neuroticism"
      },
      {
        "id": "q10",
        "text": "I see myself as someone who has an active imagination",
        "type": "likert",
        "options": [
          {"value": 1, "label": "Disagree strongly"},
          {"value": 2, "label": "Disagree a little"},
          {"value": 3, "label": "Neither agree nor disagree"},
          {"value": 4, "label": "Agree a little"},
          {"value": 5, "label": "Agree strongly"}
        ],
        "reverse_score": false,
        "dimension": "openness"
      }
    ],
    "scoring_rules": {
      "extraversion": {
        "type": "average",
        "questions": ["q1", "q6"]
      },
      "agreeableness": {
        "type": "average", 
        "questions": ["q2", "q7"]
      },
      "conscientiousness": {
        "type": "average",
        "questions": ["q3", "q8"]
      },
      "neuroticism": {
        "type": "average",
        "questions": ["q4", "q9"]
      },
      "openness": {
        "type": "average",
        "questions": ["q5", "q10"]
      }
    }
  }'::jsonb
);